### ISSUE TITLE
Background rotation

### ISSUE THREAD

**Issue by ndachel** [mbfrahry/Zirata#1]
The background appears to rotate in the opposite direction of the incoming ships. This is disorienting, and I am now dizzy.

**Comment by mbfrahry** [comment]
I didn't even notice! I'll fix that for sure! Is the background or the
enemies rotating correctly? And then I'll make the switch for the othe

**Comment by ndachel** [comment]
Looks like enemies are correct.

**Comment by mbfrahry** [comment]
Latest apk. Takes care of weird rotations and now turrets have an on/off
indicator.

**Comment by mbfrahry** [comment]
Issue closed!
